version: "3.8"

x-carte-build: &carte-build
  context: pentaho-cluster
  args:
    PENTAHO_VERSION: ${PENTAHO_VERSION}
    PDI_BUILD: ${PDI_BUILD}
    MYSQL_CONNECTOR_VERSION: ${MYSQL_CONNECTOR_VERSION}

services:
  cartemaster:
    container_name: cartemaster
    build: *carte-build
    image: cartemaster
    restart: always
    ports:
      - ${CLUSTER_MASTER_EXTERNAL_PORT}:${CLUSTER_MASTER_INTERNAL_PORT}
    environment:
      IS_MASTER: 'true'
      MASTER_PORT: ${CLUSTER_MASTER_INTERNAL_PORT}
      MASTER_IP: ${CLUSTER_MASTER_IP}

  carteslave:
    container_name: carteslave
    build: *carte-build
    image: carteslave
    restart: always
    ports:
      - ${CLUSTER_SLAVE_EXTERNAL_PORT}:${CLUSTER_SLAVE_INTERNAL_PORT}
    depends_on:
      - cartemaster

  db:
    container_name: bicenter-${INSTALLATION_ENV}-db
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  sbt:
    container_name: bicenter-${INSTALLATION_ENV}-server
    build: BIcenter
    image: bicenter:${INSTALLATION_ENV}
    restart: always
    stdin_open: ${STDIN_OPEN}
    tty: ${TTY}
    ports:
      - ${BICENTER_PORT}:9000
    volumes:
      - ..:/opt/BIcenter
    environment:
      DB_HOST: db
      DB_PORT: ${MYSQL_INTERNAL_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      INSTALLATION_ENV: ${INSTALLATION_ENV}
    depends_on:
      - db

volumes:
  db_data:
