#!/bin/bash

set -e

function runInDevMode {
	cd BIcenter && sbt run
}

function runInProdMode {
	# create distributable zip
	cd BIcenter && sbt dist

	# copy project's distributable package generated by `sbt dist`
	cp target/universal/bicenter-*.zip ../bicenter.zip

	# extract distributable package
	cd .. && unzip bicenter.zip || true && [[ -d prod ]] || mkdir prod && mv bicenter-*/* prod && rm bicenter.zip

	# copy configuration folder
	cp -r BIcenter/conf prod/conf

	# remove RUNNING_PID if exists
	cd prod && rm -rf RUNNING_PID && bash bin/bicenter
}

if [ "$INSTALLATION_ENV" == "development" ]; then
	runInDevMode
elif [ "$INSTALLATION_ENV" == "production" ]; then
	runInProdMode
else
	echo "$INSTALLATION_ENV not supported"
fi
